In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [8]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [9]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [11]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
X_train

array([[-9.09728250e-01, -1.42902837e+00, -9.54659537e-01, ...,
        -1.15066525e+00, -2.71047634e-01, -4.02973518e-01],
       [-1.25212649e+00, -5.96284267e-04, -1.24428701e+00, ...,
        -1.05248416e+00,  5.03953277e-01, -2.22575421e-01],
       [ 1.14525254e+00, -1.36641853e+00,  1.01232232e+00, ...,
        -4.73277492e-01, -1.88704298e+00, -1.41298014e+00],
       ...,
       [-2.41489892e-01,  3.28685139e-01, -2.96142633e-01, ...,
        -1.11330703e+00, -3.57346862e-01, -5.45510285e-01],
       [ 2.46227282e-02, -4.50459637e-01, -5.23585606e-02, ...,
        -5.39657787e-01, -6.34858105e-01, -1.00207337e+00],
       [ 1.96117528e-01, -5.26982785e-01,  1.38727021e-01, ...,
        -5.52470728e-01, -7.49923742e-01, -1.00931156e+00]])

In [14]:
X_test

array([[ 4.17893641, -0.1513237 ,  4.17851615, ...,  0.70134499,
        -2.11548212, -1.60562749],
       [-0.47803444, -0.13509151, -0.51250635, ..., -0.45768584,
         0.14352709, -0.68136564],
       [-0.27401477, -0.1234971 , -0.252013  , ...,  0.18110872,
         0.36350551, -0.05108587],
       ...,
       [ 1.32561776, -0.13972928,  1.29081027, ...,  0.77390019,
         1.348332  ,  0.0947916 ],
       [-0.12913123, -1.10438472, -0.15047201, ...,  0.22742055,
         0.13337424, -0.64016361],
       [-1.12261835, -0.36929872, -1.10761369, ..., -0.9002726 ,
         0.26536129,  0.21617057]])

In [15]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [16]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [47]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [48]:
X_train_tensor.shape

torch.Size([455, 30])

In [49]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [57]:
class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],dtype=torch.float32,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float32,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    return torch.sigmoid(z)
  def loss_function(self,y_pred, y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    return -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()

Parameters

In [58]:
learning_rate=0.1
epochs = 25

In [59]:
model=MySimpleNN(X_train_tensor)

In [60]:
model.weights

tensor([0.0225, 0.5907, 0.4205, 0.1810, 0.8459, 0.8778, 0.6815, 0.9622, 0.4628,
        0.3172, 0.2101, 0.8887, 0.4444, 0.0489, 0.7158, 0.5861, 0.4706, 0.4928,
        0.9368, 0.1150, 0.1189, 0.2250, 0.5817, 0.3225, 0.4947, 0.8650, 0.6481,
        0.8517, 0.2103, 0.6443], requires_grad=True)

In [61]:
model.bias

tensor([0.], requires_grad=True)

In [65]:
for epoch in range(epochs):
  y_pred=model.forward(X_train_tensor)
  loss=model.loss_function(y_pred,y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights.sub_(learning_rate*model.weights.grad)
    model.bias.sub_(learning_rate*model.bias.grad)
  model.weights.grad.zero_()
  model.bias.grad.zero_()

In [66]:
model.weights

tensor([ 0.2931,  0.7101,  0.6605,  0.4283,  0.5462,  0.5647,  0.5045,  0.9456,
         0.2034, -0.2617,  0.2438,  0.6368,  0.4356,  0.1465,  0.2642,  0.0392,
        -0.0015,  0.0833,  0.5622, -0.4875,  0.3990,  0.3988,  0.8248,  0.5679,
         0.3668,  0.6869,  0.5081,  0.8707,  0.2140,  0.3129],
       requires_grad=True)

In [68]:
model.bias

tensor([-0.1690], requires_grad=True)

In [76]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(accuracy)

tensor(0.9474)

In [77]:
y_pred

tensor([1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
        0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1.,
        0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
        1., 0., 0., 1., 0., 0.])